version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  reviewers:
  - yonycalsin
  ignore:
  - dependency-name: next
    versions:
    - 10.0.8
    - 10.1.2
    - 10.1.3
  - dependency-name: "@types/react"
    versions:
    - 17.0.3
  - dependency-name: "@types/react-dom"
    versions:
    - 17.0.2
