name: CI Workflow

on: push

jobs:
   typecheck:
      if: "! contains(toJSON(github.event.commits.*.message), '[skip ci]')"

      runs-on: ubuntu-latest

      steps:
         - uses: actions/checkout@v2

         - name: Set up node environment
           uses: actions/setup-node@v2-beta
           with:
              node-version: 12.x

         - name: Cache node modules
           id: node-modules
           uses: actions/cache@v2
           with:
              path: node_modules
              key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
              restore-keys: |
                 ${{ runner.os }}-node-

         - if: steps.node-modules.outputs.cache-hit != 'true'
           run: npm ci

         - name: Type Check
           run: npm run typecheck
