name: Release
on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node 14.17.0
        uses: actions/setup-node@v1
        with:
          node-version: 14.17.0

      - name: Install deps and build (with cache)
        uses: bahmutov/npm-install@v1

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
